#! /bin/sh

SECONDS_SINCE_LAST_RUN=`echo \`date +%s\` - 0\`stat -c%Y ${OPENSHIFT_DATA_DIR}/.update_index 2>/dev/null\` | bc`

if [ $SECONDS_SINCE_LAST_RUN -ge 300 ]; then
	source ${OPENSHIFT_HOMEDIR}/python/virtenv/bin/activate
	python ${OPENSHIFT_REPO_DIR}/openshift/manage.py update_index
	touch ${OPENSHIFT_DATA_DIR}/.update_index
fi
